name: Update README.md

on:
  push:
    branches:
      - dev
    paths:
      - "info.yml"

permissions:
  contents: write

jobs:
  call-workflow:
    uses: MaximumFX/tk-readme-generator/.github/workflows/update-readme.yml@main
